// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(FactoryDbContext))]
    partial class FactoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-rc.1.23419.6");

            modelBuilder.Entity("WebApi.ProductionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalProduction")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductionHistory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5063a8a3-ccd0-4343-80ef-30bff16624d6"),
                            Price = 0.124333m,
                            TotalProduction = 34.555556m
                        },
                        new
                        {
                            Id = new Guid("917e4e59-22e0-41b1-8b7f-7c4ee1db720c"),
                            Price = 98.343434m,
                            TotalProduction = 12.326547m
                        },
                        new
                        {
                            Id = new Guid("4165021b-6ea4-42af-95a0-c7f5c73d2a5a"),
                            Price = 49.495678m,
                            TotalProduction = 72.879476m
                        },
                        new
                        {
                            Id = new Guid("7a68206d-0ea7-4792-894e-79485d04b0b7"),
                            Price = 49.495678m,
                            TotalProduction = 72.879434m
                        },
                        new
                        {
                            Id = new Guid("37df7e04-9966-4466-95d5-7575312360b7"),
                            Price = 49.495678m,
                            TotalProduction = 72.879476m
                        },
                        new
                        {
                            Id = new Guid("c7d3f097-7906-4683-85b7-7255f22f5f5c"),
                            Price = 49.495673m,
                            TotalProduction = 72.873435m
                        },
                        new
                        {
                            Id = new Guid("a97a7106-be2e-451b-b81f-94d137bbc636"),
                            Price = 49.495673m,
                            TotalProduction = 72.879476m
                        },
                        new
                        {
                            Id = new Guid("ecb8ef4c-73c1-4018-a5fb-c9c2fe1091ee"),
                            Price = 49.495678m,
                            TotalProduction = 72.879435m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
